language: rust

cache: cargo

os:
  - linux
  - osx
  - windows

jobs:
  allow_failures:
    - os: osx

install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install libssl-dev; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install openssl;
      export OPENSSL_ROOT_DIR=$(brew --prefix openssl);
      export OPENSSL_LIB_DIR=$(brew --prefix openssl)"/lib";
      export OPENSSL_INCLUDE_DIR=$(brew --prefix openssl)"/include";
    fi
  - if [ $TRAVIS_OS_NAME = windows ];
      then choco install openssl;
      choco install visualstudio2019buildtools --package-parameters
      "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64";
    fi

script:
  - cargo build --verbose
  - cargo test ipv4 --verbose -- --test-threads=1
